version: '3.8'

services:
  # PostgreSQL container
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: studysprint-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
    ports:
      - "5432:5432"
    networks:
      - your_network_name

  # Spring Boot application container
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/studysprint-db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root123
    networks:
      - your_network_name

networks:
  your_network_name:
    driver: bridge
